# Generated by Django 3.2.5 on 2021-12-13 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0007_alter_order_date_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 13, 23, 24, 12, 266255), null=True),
        ),
    ]
